### ISSUE TITLE
The number of points

### ISSUE THREAD

**Issue by BingHan0458** [lizhuangzi/SPU#1]
Dear author, your paper was very well. I encountered an issue while reproducing your code. The number of points in Table VI is not very clear. If SPC-16 has 128 points, SPC-8 has 258 points, how many points are there with Dense and SPU-2 ×? Are they all 256 or 2048 points? Do they have the same number of points?

**Comment by lizhuangzi** [comment]
Hello, the Dense denotes results of 2048 points,  SPU-2× denotes total 256 points.
